### ISSUE TITLE
Tener un Manifesto/Start-here

### ISSUE THREAD

**Issue by ghost** [CodeandoMexico/ideas#3]
Algo entre el [manifesto de Elm](https://github.com/elm-community/Manifesto) y el [start-here de DWYL](https://github.com/dwyl/start-here). Guadalajara también tiene un [empieza-aqui](https://github.com/CodeandoGuadalajara/empieza-aqui).

Funciona como un landing page de la organización _(pero para GitHub... igual y hasta pueden sacar un github page para este doc)_. :ok_hand:

**Comment by miguelsalazar** [comment]
Estamos trabajando en estos documentos. En estos días los abriré para recibir feedback de la comunidad.

**Comment by rubenrivera** [comment]
¿Cómo va esto? ¿Cómo podría participar?

**Comment by miguelsalazar** [comment]
El tema del manifiesto sigue presente y de hecho esta semana vamos a tener un avance sobre el tema. La idea es que tomemos información de la encuesta de identidad que realizamos en marzo para identificar los conceptos clave que debe tener el manifiesto.

Vale la pena seguir el repositorio de [CodeandoMexico/comunidad](http://github.com/CodeandoMexico/comunidad) para estar al tanto. Creo que la discusión también la podemos llevar en los issues de aquel repositorio.
