### ISSUE TITLE
Agregar una entrada sobre Codeando México en Wikipedia

### ISSUE THREAD

**Issue by ghost** [CodeandoMexico/ideas#4]
Quiénes empezaron, por qué, qué se ha hecho, proyectos chidos, links a repos...
A fin de cuentas, es una herramienta de exposure.

**Comment by miguelsalazar** [comment]
Quizá valdría la pena empezar por un wiki interno (http://wiki.codeandomexico.org). Si agregamos la entrada a Wikipedia me da la impresión de que la bajarían.
