### ISSUE TITLE
Agregar un Roadmap de la organización

### ISSUE THREAD

**Issue by ghost** [CodeandoMexico/ideas#5]
Así podemos saber hacia dónde va, en qué se está trabajando ahorita, y con qué podemos ayudar como comunidad. También sirve para que los chapters locales no dupliquen esfuerzos del team central de Codeando México.

**Comment by miguelsalazar** [comment]
El roadmap está definido y próximamente lo publicaremos en la siguiente actualización de codeandomexico.org

**Comment by miguelsalazar** [comment]
Un roadmap público podría funcionar, estilo:
https://trello.com/b/2xc7Q0kd/labs-public-product-roadmap
