### ISSUE TITLE
Bot para Slack que fordwardié noticias a redes sociales

### ISSUE THREAD

**Issue by ghost** [CodeandoMexico/ideas#6]
Creo que ya existe, pero no me acuerdo cómo se llama la integración.

La idea es que cuando postées un link en algún canal de Slack, te pregunte si aparte lo quieres compartir en news.codeandomexico.org / facebook / etc.

Así, la misma comunidad puede ir nutriendo el news feed con un algo que ya están acostumbrados (compartir contenido en Slack).

**Comment by miguelsalazar** [comment]
@MrOutis: ¿De Slack directamente al Facebook de Codeando? ¿No crees que se podría volver algo caótico?

**Comment by ghost** [comment]
Sí, tienes razón, @miguelsalazar
